-- 文件管理系統 資料庫 Schema
-- 每次啟動時執行，所有 CREATE TABLE 皆使用 IF NOT EXISTS

-- 使用者
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    name TEXT NOT NULL,
    department TEXT DEFAULT '',
    email TEXT DEFAULT '',
    is_admin INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 群組
CREATE TABLE IF NOT EXISTS groups_tbl (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    description TEXT DEFAULT ''
);

-- 群組成員
CREATE TABLE IF NOT EXISTS group_members (
    group_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    PRIMARY KEY (group_id, user_id),
    FOREIGN KEY (group_id) REFERENCES groups_tbl(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 頁籤 (tab_type: public / personal)
CREATE TABLE IF NOT EXISTS tabs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    owner_id INTEGER,
    tab_type TEXT NOT NULL CHECK(tab_type IN ('public','personal')),
    order_no INTEGER DEFAULT 0,
    FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 資料夾（階層，parent_id NULL = 根層）
CREATE TABLE IF NOT EXISTS folders (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    description TEXT DEFAULT '',
    tab_id INTEGER NOT NULL,
    parent_id INTEGER,
    owner_id INTEGER NOT NULL,
    order_no INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (tab_id) REFERENCES tabs(id) ON DELETE CASCADE,
    FOREIGN KEY (parent_id) REFERENCES folders(id) ON DELETE CASCADE,
    FOREIGN KEY (owner_id) REFERENCES users(id)
);

-- 資料夾授權
CREATE TABLE IF NOT EXISTS folder_permissions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    folder_id INTEGER NOT NULL,
    user_id INTEGER,
    group_id INTEGER,
    can_read INTEGER DEFAULT 1,
    can_edit INTEGER DEFAULT 0,
    can_delete INTEGER DEFAULT 0,
    FOREIGN KEY (folder_id) REFERENCES folders(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (group_id) REFERENCES groups_tbl(id) ON DELETE CASCADE
);

-- 檔案類型
CREATE TABLE IF NOT EXISTS file_types (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    code TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    description TEXT DEFAULT ''
);

-- 文件主表
CREATE TABLE IF NOT EXISTS documents (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    doc_number TEXT UNIQUE NOT NULL,
    version INTEGER DEFAULT 1,
    subject TEXT NOT NULL,
    issue_date DATE NOT NULL,
    file_type_id INTEGER,
    department TEXT DEFAULT '',
    remarks TEXT DEFAULT '',
    is_encrypted INTEGER DEFAULT 0,
    encrypt_password TEXT DEFAULT '',
    original_filename TEXT DEFAULT '',
    stored_filename TEXT DEFAULT '',
    folder_id INTEGER NOT NULL,
    owner_id INTEGER NOT NULL,
    is_locked INTEGER DEFAULT 0,
    locked_by INTEGER DEFAULT NULL,
    is_deleted INTEGER DEFAULT 0,
    sign_status TEXT DEFAULT '',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (file_type_id) REFERENCES file_types(id),
    FOREIGN KEY (folder_id) REFERENCES folders(id),
    FOREIGN KEY (owner_id) REFERENCES users(id)
);

-- 文件版本履歷
CREATE TABLE IF NOT EXISTS document_versions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    document_id INTEGER NOT NULL,
    version INTEGER NOT NULL,
    original_filename TEXT DEFAULT '',
    stored_filename TEXT DEFAULT '',
    created_by INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE CASCADE,
    FOREIGN KEY (created_by) REFERENCES users(id)
);

-- 文件授權（分享）
CREATE TABLE IF NOT EXISTS document_permissions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    document_id INTEGER NOT NULL,
    user_id INTEGER,
    group_id INTEGER,
    can_read   INTEGER DEFAULT 1,
    can_edit   INTEGER DEFAULT 0,
    can_delete INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (group_id) REFERENCES groups_tbl(id) ON DELETE CASCADE
);

-- ── 初始資料 ──────────────────────────────────────────────────
-- 管理員帳號（admin / admin123）
-- admin / admin123  (hash generated by werkzeug scrypt)
INSERT OR IGNORE INTO users (username, password_hash, name, department, is_admin)
VALUES ('admin',
        'scrypt:32768:8:1$vaNoGqZCt2yVw3uE$e69735e6f6d23644b9f10a6da8f936090a491f95498da9020ee8af5c82814620b1a6e0f817bdf1cd5274a7283684fd588b3203e4e3cfbe98f26019f9b3a6f173',
        '系統管理員', '資訊部', 1);

-- 公共文件頁籤
INSERT OR IGNORE INTO tabs (id, name, owner_id, tab_type, order_no)
VALUES (1, '公共文件', NULL, 'public', 0);

-- 預設檔案類型
INSERT OR IGNORE INTO file_types (code, name, description) VALUES ('GEN', '一般文件', '');
INSERT OR IGNORE INTO file_types (code, name, description) VALUES ('CTR', '合約', '');
INSERT OR IGNORE INTO file_types (code, name, description) VALUES ('DWG', '圖面', '');
INSERT OR IGNORE INTO file_types (code, name, description) VALUES ('RPT', '報告', '');
INSERT OR IGNORE INTO file_types (code, name, description) VALUES ('SOP', '標準作業程序', '');

-- 下載稽核紀錄
CREATE TABLE IF NOT EXISTS download_logs (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    doc_id        INTEGER NOT NULL,
    doc_number    TEXT    NOT NULL,
    subject       TEXT    NOT NULL,
    doc_path      TEXT    NOT NULL,
    user_id       INTEGER NOT NULL,
    user_name     TEXT    NOT NULL,
    downloaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (doc_id)  REFERENCES documents(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);
CREATE INDEX IF NOT EXISTS idx_dl_logs_user ON download_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_dl_logs_doc  ON download_logs(doc_id);
CREATE INDEX IF NOT EXISTS idx_dl_logs_ts   ON download_logs(downloaded_at);

-- ═══════════════════════════════════════════════════════════════
-- ISO 9001:2015 — 審核工作流程
-- ═══════════════════════════════════════════════════════════════

-- 審核人員角色池（管理員設定）
CREATE TABLE IF NOT EXISTS approver_roles (
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role_type  TEXT NOT NULL CHECK(role_type IN ('reviewer','approver')),
    UNIQUE(user_id, role_type)
);

-- 工作流程（每次送審一筆）
CREATE TABLE IF NOT EXISTS approval_workflows (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    document_id   INTEGER NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    initiated_by  INTEGER NOT NULL REFERENCES users(id),
    initiated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status        TEXT NOT NULL DEFAULT 'open'
                  CHECK(status IN ('open','approved','rejected','withdrawn')),
    closed_at     TIMESTAMP DEFAULT NULL
);
CREATE INDEX IF NOT EXISTS idx_wf_doc    ON approval_workflows(document_id);
CREATE INDEX IF NOT EXISTS idx_wf_status ON approval_workflows(status);

-- 工作流程步驟
CREATE TABLE IF NOT EXISTS workflow_steps (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    workflow_id  INTEGER NOT NULL REFERENCES approval_workflows(id) ON DELETE CASCADE,
    step_order   INTEGER NOT NULL,
    step_type    TEXT NOT NULL CHECK(step_type IN ('review','approve')),
    assignee_id  INTEGER NOT NULL REFERENCES users(id),
    status       TEXT NOT NULL DEFAULT 'pending'
                 CHECK(status IN ('pending','approved','rejected','skipped')),
    comments     TEXT DEFAULT '',
    acted_at     TIMESTAMP DEFAULT NULL
);
CREATE INDEX IF NOT EXISTS idx_ws_workflow ON workflow_steps(workflow_id);
CREATE INDEX IF NOT EXISTS idx_ws_assignee ON workflow_steps(assignee_id, status);

-- 簽核流程範本
CREATE TABLE IF NOT EXISTS workflow_templates (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    name        TEXT NOT NULL,
    description TEXT DEFAULT '',
    is_active   INTEGER DEFAULT 1,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 簽核流程範本步驟
CREATE TABLE IF NOT EXISTS workflow_template_steps (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    template_id INTEGER NOT NULL REFERENCES workflow_templates(id) ON DELETE CASCADE,
    step_order  INTEGER NOT NULL,
    step_type   TEXT NOT NULL CHECK(step_type IN ('review','approve')),
    user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_wts_template ON workflow_template_steps(template_id);

-- 完整稽核日誌（ISO 7.5 要求）
CREATE TABLE IF NOT EXISTS audit_log (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    doc_id      INTEGER REFERENCES documents(id) ON DELETE SET NULL,
    doc_number  TEXT NOT NULL DEFAULT '',
    action      TEXT NOT NULL,
    actor_id    INTEGER REFERENCES users(id) ON DELETE SET NULL,
    actor_name  TEXT NOT NULL DEFAULT '',
    details     TEXT DEFAULT '',
    ip_address  TEXT DEFAULT '',
    logged_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_al_doc    ON audit_log(doc_id);
CREATE INDEX IF NOT EXISTS idx_al_actor  ON audit_log(actor_id);
CREATE INDEX IF NOT EXISTS idx_al_action ON audit_log(action);
CREATE INDEX IF NOT EXISTS idx_al_ts     ON audit_log(logged_at);
